#version 450

layout(local_size_x = 16, local_size_y = 16) in;

layout(binding = 0, rgba8) uniform readonly image2D inputImage;
layout(binding = 1, rgba8) uniform writeonly image2D outputImage;

const ivec2 offsets[9] =
    {
        ivec2(-1, -1),
        ivec2(0, -1),
        ivec2(1, -1),
        ivec2(-1, 0),
        ivec2(0, 0),
        ivec2(1, 0),
        ivec2(-1, 1),
        ivec2(0, 1),
        ivec2(1, 1),
    };

const float kernel[9] =
    {
        0.0,
        -1.0,
        0.0,
        -1.0,
        5.0,
        -1.0,
        0.0,
        -1.0,
        0.0
    };

void main()
{
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(inputImage);

    vec4 sum = vec4(0.0);

    for (int i = 0; i < 9; i++)
    {
        ivec2 samplePos = clamp(pixel + offsets[i], ivec2(0), size - 1);

        sum += imageLoad(inputImage, samplePos) * kernel[i];
	}

	imageStore(outputImage, pixel, sum);
}
